# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - x86
  - x64

# Build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# Specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON

# Scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# Scripts that run after cloning repository
install:
  - appveyor-retry choco install doxygen.portable
  - appveyor-retry choco install graphviz.portable
  - cmd: git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cmd: cd scripts
  - cmd: if "%platform%"=="x86" 01-generate-VisualStudio-x32.bat
  - cmd: if "%platform%"=="x64" 01-generate-VisualStudio-x64.bat
  - cmd: 02-build-VisualStudio.bat
  - cmd: 03-tests.bat
  - cmd: 04-install-VisualStudio.bat
  - cmd: 05-doxygen-VisualStudio.bat
  - cmd: 06-clean.bat

# Test scripts
test: off

# Don't send notifications on success
notifications:
  - provider: Email
    on_build_success: false
