# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 5

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
#    - build: VisualStudio
#      ext: bat
#      command: cmd
#      prefix:
    - build: Cygwin
      ext: sh
      command: C:\cygwin\bin\bash -lc
      prefix: cd $APPVEYOR_BUILD_FOLDER/scripts; exec 0</dev/null;

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - if "%build%"=="VisualStudio" msbuild /version
  - if "%build%"=="Cygwin" %command% "cygcheck -dc cygwin"
  - '%command% "cmake --version"'

# Scripts that run after cloning repository
install:
  - if "%build%"=="VisualStudio" choco install doxygen.portable
  - if "%build%"=="VisualStudio" choco install graphviz.portable
  - git config --global user.name "AppVeyor"
  - git config --global user.email "team@appveyor.com"
  - git config --global push.default simple
  - git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cd scripts
  - '%command% "%prefix% ./01-generate-%build%.%ext%"'
  - '%command% "%prefix% ./02-build-%build%.%ext%"'
  - '%command% "%prefix% ./03-tests.%ext%"'
  - '%command% "%prefix% ./04-install-%build%.%ext%"'
  - '%command% "%prefix% ./05-doxygen-%build%.%ext%"'
  - '%command% "%prefix% ./06-clean.%ext%"'

# Test scripts
test: off
